[build]
  command = "ng build --configuration production --base-href /wortHafen/"
  publish = "dist/wortHafen/browser"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy"
  status = 200

# برای Single Page App routing
[[redirects]]
  from = "/wortHafen/*"
  to = "/wortHafen/index.html"
  status = 200
