[build]
  command = "npm run build"
  publish = "dist/wortHafen/browser"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy"
  status = 200
