[build]
  command = "ng build --configuration production --base-href /worthafen/"
  publish = "dist/worthafen/browser"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy"
  status = 200
